# Hardcoded svn paths
:svn_paths:
  :foundation: /var/tools/secretary/foundation
  :officers:   /var/tools/secretary/foundation/officers
  :documents:  /var/tools/secretary/documents
  :received:   /var/tools/secretary/documents/received
  :subreq:     /var/tools/secretary/subreq

# Update these users when they change
:secretary:
  - clr
  - rubys
  - jcarman
  - sanders
  - mnour
